Shape list
CapsRePeaT/Overheat pull request #24
Opened 2022-04-10 23:31 UTC by CapsRePeaT

1. fixed compilation
2. added option to choose between 2d and 3d file loading
3. added functionality of remembering dirs in file dilog when choose second file

2022-04-10 23:36 UTC, CapsRePeaT commented on src/common/include/common.h
> +	count,
Count (upper)

2022-04-10 23:36 UTC, CapsRePeaT commented on src/common/include/common.h
> +	count,
Count (upper)

2022-04-10 23:36 UTC, CapsRePeaT commented on src/core/src/core.cpp
> +	//new_representation.heatmaps()     = reader.heatmaps();
delete

2022-04-10 23:44 UTC, Saiel requested changes
Tab aligning must be fixed before merging, sorry. The rest seems ok

2022-04-10 23:44 UTC, Saiel commented on src/core/include/core.h
> +									  std::string t2d_file_path_mv,
Do not use tabs for aligning. Thery are only for indent, that is level 1 here. The rest should be spaces

2022-04-10 23:44 UTC, Saiel commented on src/core/src/core.cpp
> +												const GeometryType type) {
Same as in header. Also trailing space on 9th line

2022-04-10 23:44 UTC, Saiel commented on src/ui/src/mainwindow.h
> +								std::string t2d_file_path,
Same as in `core.h`.
Trailing space

2022-04-11 00:02 UTC, Saiel requested changes

2022-04-11 00:02 UTC, Saiel commented on src/ui/src/mainwindow.cpp
> +																												absolute_trm_dir,
84th line exceeds line size limit

2022-04-11 00:04 UTC, CapsRePeaT commented on src/ui/src/mainwindow.cpp
> +																												absolute_trm_dir,
80 not a strict limit, if you go a bit more but improve readibility it's ok

2022-04-11 00:09 UTC, Saiel approved these changes

2022-04-11 00:10 UTC, merged